### ISSUE TITLE
YouTube URLs don't work

### ISSUE THREAD

**Issue by dbogdanov** [MTG/essentia-replicate-demos#14]
Error:

```
ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1585, in _decrypt_signature func = self._extract_signature_function( File "/usr/local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1507, in _extract_signature_function res = self._parse_sig_js(code) File "/usr/local/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1573, in _parse_sig_js initial_function = jsi.extract_function(funcname) File "/usr/local/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 995, in extract_function self.extract_function_from_code(*self.extract_function_code(funcname)), File "/usr/local/lib/python3.10/site-packages/youtube_dl/jsinterp.py", line 988, in extract_function_code code, _ = self._separate_at_paren(func_m.group('code')) # refine the match AttributeError: 'NoneType' object has no attribute 'group' (caused by AttributeError("'NoneType' object has no attribute 'group'")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Tested with https://replicate.com/mtg/music-arousal-valence

@palonso @xaviliz

**Comment by jasongrishkoff** [comment]
Hey, a few months ago I encountered this on my side. The issue is that YouTube now does a bunch of extra checks to verify that the user requesting data is real - thus rendering yt-dl (and yt-dlp) effectively useless. 

For example: https://github.com/yt-dlp/yt-dlp/issues/10128

My suggestion would be to remove this from the demo docs / replicate version, and simply require an MP3.  Uses who want to integrate their own workaround for YouTube can do that prior to providing the MP3.
